### ISSUE TITLE
Could not predict the result with uploaded matrix

### ISSUE THREAD

**Issue by likelet** [bioinformatist/CrossICC#5]
One of the users raise the question that they could not get the result from an upload data matrix, with the following error message:
![image](https://user-images.githubusercontent.com/3021506/117594975-08fb3100-b172-11eb-9607-cd955b560745.png)

However, i could not reproduce such error with dataset they provided. 
A possible solution is that to rerun the analysis under the command version   A typical R codes under R console are below:    

```R
library(CrossICC)
yourdataset<-read.csv("GSE87466_for_predict.txt",header=T,row.names=1, check.names=F)
# `CrossICC.object` was generated by your previous step with crossICC, 
#   which could be found at the home folder in your computer, you can read it by 

CrossICC.object<-readRDS("~/CrossICC.object.rds")

# then perform prediction
predicted <- predictor(as.matrix(yourdataset), CrossICC.object)

``` 
Please let me know if you have any other question.

**Comment by likelet** [comment]
We have updated the prediction panel in shiny app which provide downloading an example csv dataset. 

Please download and install the latest version of CrossICC   from github.

**Comment by msc245** [comment]
Thanks so much for your reply! Yeah, actually I could get the result by using the  "predictor" function directly in R (read.csv,readRDS and then predictor, as you wrote)... However when I use the shiny app it will output the "invalid subscript type "list" "error...
BTW, the CrossICC.object.rds in your example is generated by my GSE? Could you please send me the CrossICC.object so that I can test it in my shiny

**Comment by msc245** [comment]
Thanks so much for your reply! Yeah, actually I could get the result by using the  "predictor" function directly in R (read.csv,readRDS and then predictor, as you wrote)... However when I use the shiny app it will output the "invalid subscript type "list" "error...
BTW, the CrossICC.object.rds in your example is generated by my GSE? Could you please send me the CrossICC.object so that I can test it in my shiny

**Comment by likelet** [comment]
hi, thanks for using our package. the `CrossICC.object.rds ` is from our own example dataset.  for your case, you need build your clustering frist with `CrossICC` function.

**Comment by msc245** [comment]
Thanks. I have re-tried the shiny with great carefulness with some new datasets, however the same bug was output. I wonder if you could please use my datasets and my steps to see if there will be a bug. 
I know it will take you some time but  I really want to figure out if it is really due to the version or any other rare problem. I would be grateful for your work!
Files are in https://github.com/msc245/Files-for-CrossICC
pipelines are as follows
#####1.we use 1_for_crossicc.txt 2_for_crossicc.txt for construction######
 library(CrossICC)
##### input 2 files
exp.files <- list.files(path = ".", pattern = "txt") 
CrossICC.input <- CrossICCInput(exp.files)
CrossICC.object <- CrossICC(CrossICC.input, use.shiny = T, overwrite = TRUE, output.dir = '.')
#####2.then in the shiny,we first upload the default rds in the shiny( in shiny app but not in R) 
#####3.then we upload the matrix for_prediction.txt in "Allocate new samples" modulem, submit 
#####4. in our app, the bug "invalid subscript type 'list'" appeared.
![image](https://user-images.githubusercontent.com/56242608/118009925-19cdc180-b381-11eb-8dc7-14ba7806243c.png)

**Comment by msc245** [comment]
![image](https://user-images.githubusercontent.com/56242608/118010052-3cf87100-b381-11eb-9bc5-90f3a0f33495.png)

**Comment by likelet** [comment]
thanks for your detailed information. Sorry for the inconvenience of the shiny APP. I have been outside those days and really sorry  for not testing your dataset immediatbly. Could you plz try to reinstall the package as I have committed a fixed version few days before ( It seems that you did not update the package from GitHub). 
```R
devtools::install_github("bioinformatist/CrossICC")
```
Plz let me your progress. 

Qi
